smirnovadev/practicum-android-diploma

- app/src/main/res/color/button_navigate_selected.xml
- app/src/main/res/layout/activity_root.xml
- app/src/main/res/values/dimens.xml
Подготовил rootActivity и создал FragmentContsinerView
>  RootActivity

- app/src/main/java/ru/practicum/android/diploma/presentation/DevelopersFragment.kt
- app/src/main/java/ru/practicum/android/diploma/ui/root/RootActivity.kt
- app/src/main/res/layout/fragment_developers.xml
- app/src/main/res/menu/bottom_navigate_menu.xml
- app/src/main/res/navigation/main_navigation_graph.xml
Дополнил RootActivity, исправил ошибку во Фрагменте Команды и в верстке developers заменил на тулбар
> BottomNavigationGraph and NavController

- app/src/main/res/layout/fragment_developers.xml
- app/src/main/res/layout/fragment_favorites.xml
- app/src/main/res/layout/fragment_search.xml
- app/src/main/res/values/styles.xml
Рефакторинг тулбаров существующих экранов. Добавление стиля Toolbar.
> Рефакторинг Toolbar.

- app/src/main/java/ru/practicum/android/diploma/search/ui/SearchFragment.kt
- app/src/main/res/layout/fragment_search.xml
Реализовал отображение ошибок через один TextView.
> Доработка экрана Search.

- app/src/main/java/ru/practicum/android/diploma/search/ui/adapter/SearchAdapter.kt
- app/src/main/java/ru/practicum/android/diploma/search/ui/adapter/SearchClickListener.kt
- app/src/main/java/ru/practicum/android/diploma/search/ui/adapter/SearchViewHolder.kt
Создан adapter и viewHolder
При готов запросе, нужно будет смотреть и поправлять информацию получаемую с сервера
> adapter and viewHolder

- app/src/main/java/ru/practicum/android/diploma/util/Formatter.kt
Создал объект Formatter. Добавил функцию склонения слов.
> Utils. Создал объект Formatter.

- app/src/main/java/ru/practicum/android/diploma/data/dto/responses/VacancyByIdResponse.kt
- app/src/main/java/ru/practicum/android/diploma/data/dto/responses/fields/SearchVacanciesUnit.kt
- app/src/main/java/ru/practicum/android/diploma/db/AppDatabase.kt
- app/src/main/java/ru/practicum/android/diploma/db/dao/AreasDao.kt
- app/src/main/java/ru/practicum/android/diploma/db/dao/IndustriesDao.kt
- app/src/main/java/ru/practicum/android/diploma/db/dao/VacanciesDao.kt
- app/src/main/java/ru/practicum/android/diploma/db/entities/AreaEntity.kt
- app/src/main/java/ru/practicum/android/diploma/db/entities/EmployerEntity.kt
- app/src/main/java/ru/practicum/android/diploma/db/entities/IndustryEntity.kt
- app/src/main/java/ru/practicum/android/diploma/db/entities/VacancyEntity.kt
- app/src/main/java/ru/practicum/android/diploma/di/DataModule.kt
AppDatabase
Базовые запросы Dao
Entities
> Diplom 42 database

- app/src/main/java/ru/practicum/android/diploma/data/dto/responses/fields/Phone.kt
- app/src/main/java/ru/practicum/android/diploma/data/dto/responses/fields/Salary.kt
> DIPLOM-13 - types

- app/src/main/java/ru/practicum/android/diploma/data/dto/responses/fields/Employer.kt
- app/src/main/java/ru/practicum/android/diploma/data/dto/responses/fields/Salary.kt
- app/src/main/java/ru/practicum/android/diploma/data/dto/responses/fields/SearchVacanciesUnit.kt
- app/src/main/java/ru/practicum/android/diploma/di/DataModule.kt
- app/src/main/java/ru/practicum/android/diploma/di/InteractorModule.kt
- app/src/main/java/ru/practicum/android/diploma/di/RepositoryModule.kt
- app/src/main/java/ru/practicum/android/diploma/di/ViewModelModule.kt
- app/src/main/java/ru/practicum/android/diploma/search/data/SearchRepositoryImpl.kt
- app/src/main/java/ru/practicum/android/diploma/search/data/mapper/VacancyMapper.kt
- app/src/main/java/ru/practicum/android/diploma/search/domain/SearchRepository.kt
- app/src/main/java/ru/practicum/android/diploma/search/domain/api/SearchInteractor.kt
- app/src/main/java/ru/practicum/android/diploma/search/domain/api/SearchRepository.kt
- app/src/main/java/ru/practicum/android/diploma/search/domain/impl/SearchInteractorImpl.kt
- app/src/main/java/ru/practicum/android/diploma/search/domain/model/VacancySnippet.kt
- app/src/main/java/ru/practicum/android/diploma/search/presentation/SearchScreenState.kt
- app/src/main/java/ru/practicum/android/diploma/search/presentation/SearchViewModel.kt
- app/src/main/java/ru/practicum/android/diploma/search/ui/SearchFragment.kt
создали класс VacancyMapper, функцию formatSalary для форматирования …зарплаты.
Создали модель VacancySnippet для экрана поиска и добавили в репозиторий функцию getVacancies
> Создание SearchRepository

- app/src/main/AndroidManifest.xml
- app/src/main/java/ru/practicum/android/diploma/data/dto/responses/fields/EmploymentDTO.kt
- app/src/main/java/ru/practicum/android/diploma/data/dto/responses/vacancies/VacancyDTO.kt
- app/src/main/java/ru/practicum/android/diploma/di/DataModule.kt
- app/src/main/java/ru/practicum/android/diploma/job/domain/JobScreenState.kt
- app/src/main/java/ru/practicum/android/diploma/job/ui/JobFragment.kt
- app/src/main/java/ru/practicum/android/diploma/job/ui/viewmodel/JobViewModel.kt
- app/src/main/java/ru/practicum/android/diploma/search/data/mapper/EmploymentMapper.kt
- app/src/main/java/ru/practicum/android/diploma/search/data/mapper/SnippetMapper.kt
- app/src/main/java/ru/practicum/android/diploma/search/data/mapper/VacancyMapper.kt
- app/src/main/java/ru/practicum/android/diploma/search/domain/model/Vacancy.kt
- app/src/main/java/ru/practicum/android/diploma/search/domain/model/fields/Employment.kt
- app/src/main/java/ru/practicum/android/diploma/search/domain/model/fields/Snippet.kt
- app/src/main/java/ru/practicum/android/diploma/search/ui/SearchFragment.kt
- app/src/main/java/ru/practicum/android/diploma/search/ui/adapter/SearchViewHolder.kt
- app/src/main/res/layout/fragment_vacancy.xml
Реализовал передачу информации. Отсутствует информация в разделах Комментарий и Условия.
Также приходит пустой список ключевых навыков
> Переход на экран "Вакансия"

- app/src/main/java/ru/practicum/android/diploma/job/ui/JobFragment.kt
- app/src/main/java/ru/practicum/android/diploma/search/ui/SearchFragment.kt
- app/src/main/res/layout/fragment_vacancy.xml
Добавил clickDebounce. Добавил paddingBottom на экране Вакансия. Добавил _binding = null в onDestroyView JobFragment.
> Поиск. СlickDebounce.

- app/src/main/java/ru/practicum/android/diploma/job/ui/JobFragment.kt
- app/src/main/java/ru/practicum/android/diploma/search/presentation/SearchViewModel.kt
- app/src/main/java/ru/practicum/android/diploma/search/ui/SearchFragment.kt
- app/src/main/res/layout/card_item.xml
- app/src/main/res/layout/fragment_vacancy.xml
Исправил верстку логотипов. Исправил ошибку с повторным запросом при очистке поисковой строки.
> Поиск. Исправления debounce, верстки

- app/src/main/java/ru/practicum/android/diploma/db/dao/FavoritesVacanciesDao.kt
- app/src/main/java/ru/practicum/android/diploma/db/entities/VacancyEntity.kt
- app/src/main/java/ru/practicum/android/diploma/di/ViewModelModule.kt
- app/src/main/java/ru/practicum/android/diploma/favorites/data/FavoritesRepositoryImpl.kt
- app/src/main/java/ru/practicum/android/diploma/favorites/domain/FavoritesInteractor.kt
- app/src/main/java/ru/practicum/android/diploma/favorites/domain/FavoritesInteractorImpl.kt
- app/src/main/java/ru/practicum/android/diploma/favorites/domain/FavoritesRepository.kt
- app/src/main/java/ru/practicum/android/diploma/favorites/ui/FavoritesFragment.kt
- app/src/main/java/ru/practicum/android/diploma/job/ui/JobFragment.kt
- app/src/main/java/ru/practicum/android/diploma/job/ui/viewmodel/JobViewModel.kt
- app/src/main/java/ru/practicum/android/diploma/search/ui/SearchFragment.kt
Рефакторинг логики. Избранные вакансии должны быть доступны без интернета.
> Избранное. Рефакторинг логики.

- app/src/main/java/ru/practicum/android/diploma/favorites/data/FavoritesRepositoryImpl.kt
- app/src/main/java/ru/practicum/android/diploma/favorites/domain/FavoritesInteractor.kt
- app/src/main/java/ru/practicum/android/diploma/favorites/domain/FavoritesInteractorImpl.kt
- app/src/main/java/ru/practicum/android/diploma/favorites/domain/FavoritesRepository.kt
- app/src/main/java/ru/practicum/android/diploma/job/ui/JobFragment.kt
- app/src/main/java/ru/practicum/android/diploma/job/ui/viewmodel/JobViewModel.kt
Рефакторинг. Не работала иконка "В избранном"
> Избранное. Рефакторинг. Не работала иконка "В избранном"

- app/src/main/java/ru/practicum/android/diploma/job/domain/impl/JobInteractorImpl.kt
- app/src/main/java/ru/practicum/android/diploma/search/domain/model/Vacancy.kt
- app/src/main/java/ru/practicum/android/diploma/search/domain/model/fields/Address.kt
- app/src/main/java/ru/practicum/android/diploma/search/domain/model/fields/Contacts.kt
- app/src/main/java/ru/practicum/android/diploma/search/domain/model/fields/Employer.kt
- app/src/main/java/ru/practicum/android/diploma/search/domain/model/fields/Employment.kt
- app/src/main/java/ru/practicum/android/diploma/search/domain/model/fields/Experience.kt
- app/src/main/java/ru/practicum/android/diploma/search/domain/model/fields/KeySkill.kt
- app/src/main/java/ru/practicum/android/diploma/search/domain/model/fields/LogoUrls.kt
- app/src/main/java/ru/practicum/android/diploma/search/domain/model/fields/Phone.kt
- app/src/main/java/ru/practicum/android/diploma/search/domain/model/fields/Schedule.kt
- app/src/main/java/ru/practicum/android/diploma/search/domain/model/fields/VacancyArea.kt
- app/src/main/java/ru/practicum/android/diploma/search/ui/SearchFragment.kt
- app/src/main/java/ru/practicum/android/diploma/search/ui/SearchFragmentStateHandler.kt
Слияние Iteration 2 с устраненными замечаниями detekt.
> Iteration 2 - слияние с develop

- app/src/main/java/ru/practicum/android/diploma/developers/DevelopersFragment.kt
- app/src/main/java/ru/practicum/android/diploma/search/presentation/SearchScreenState.kt
- app/src/main/java/ru/practicum/android/diploma/search/presentation/SearchViewModel.kt
- app/src/main/java/ru/practicum/android/diploma/search/ui/SearchFragment.kt
- app/src/main/java/ru/practicum/android/diploma/search/ui/SearchFragmentStateHandler.kt
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
Переделал обработку ошибок при постраничной загрузке поисковых результатов.
> Поиск. Рефакторинг отработки ошибок.

- app/src/main/java/ru/practicum/android/diploma/filters/ui/area/CountryFragment.kt
- app/src/main/java/ru/practicum/android/diploma/filters/ui/area/RegionFragment.kt
- app/src/main/java/ru/practicum/android/diploma/filters/ui/industry/IndustryFragment.kt
Исправил параметр в функциях Search Debounce на экранах отраслей и регионов.
> Фильтры. Некорректно работала функция Search Debounce.

- app/src/main/java/ru/practicum/android/diploma/filters/ui/area/AreaViewHolder.kt
- app/src/main/res/layout/area_item.xml
> исправление замечания: Не работает клик по стрелке в регионах и странах

- app/src/main/java/ru/practicum/android/diploma/search/ui/SearchFragment.kt
- app/src/main/res/drawable/ic_arrow_forward.xml
- app/src/main/res/drawable/ic_close_black.xml
- app/src/main/res/drawable/ic_search_black.xml
- app/src/main/res/layout/fragment_filter.xml
- app/src/main/res/layout/fragment_industry.xml
- app/src/main/res/layout/fragment_place_to_work.xml
- app/src/main/res/layout/fragment_select_country.xml
- app/src/main/res/layout/fragment_select_region.xml
- app/src/main/res/values-night/themes.xml
- app/src/main/res/values/styles.xml
- app/src/main/res/values/themes.xml
Правка верстки. Выравнивание. Стили поисковых полей. Ночная тема.
> Фильтры. Правка верстки. Выравнивание. Стили поисковых полей.

- app/src/main/java/ru/practicum/android/diploma/RootActivity.kt
- app/src/main/res/layout/activity_root.xml
BottomNavigation. Отключил видимость верхней линии на необходимых экранах.
> BottomNavigation. Divider Fix

- app/src/main/java/ru/practicum/android/diploma/filters/data/FiltersTransformRepositoryImpl.kt
- app/src/main/java/ru/practicum/android/diploma/search/presentation/SearchViewModel.kt
- app/src/main/java/ru/practicum/android/diploma/search/ui/SearchFragment.kt
Исправил отображение количества результатов. Добавил возможность повторного запроса через ACTION_DONE, если отсутствовал интернет. Доработал поиск по отраслям.
> Поиск. Количество результатов. Доработка поиска по отраслям.

- app/src/main/java/ru/practicum/android/diploma/filters/ui/FiltersFragment.kt
- app/src/main/res/layout/fragment_filter.xml
- app/src/main/res/values/styles.xml
Убрал сброс фильтров при нажатии на кнопку Назад тулбара. Добавил отображение выбранной отрасли в 2 строки.
> Фильтры. Убрал сброс фильтров при нажатии на кнопку Назад тулбара.

- app/src/main/java/ru/practicum/android/diploma/filters/domain/FiltersInteractorImpl.kt
- app/src/main/java/ru/practicum/android/diploma/filters/presentation/CountryViewModel.kt
- app/src/main/java/ru/practicum/android/diploma/filters/presentation/RegionViewModel.kt
Удалили страны из регионов. Сохранили одинаковый порядок для стран при загрузке через сеть и из БД
> Работа с экраном фильтрации

- app/src/main/java/ru/practicum/android/diploma/filters/presentation/RegionViewModel.kt
Дополнительные страны не показываются, если не выбран пункт "Другие страны"
> Другие регионы
